/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresentesRouteImport } from './routes/presentes'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as InformacoesRouteImport } from './routes/informacoes'
import { Route as ConfirmacaoRouteImport } from './routes/confirmacao'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagamentoSucessoRouteImport } from './routes/pagamento.sucesso'
import { Route as PagamentoPendenteRouteImport } from './routes/pagamento.pendente'
import { Route as PagamentoFalhaRouteImport } from './routes/pagamento.falha'

const PresentesRoute = PresentesRouteImport.update({
  id: '/presentes',
  path: '/presentes',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const InformacoesRoute = InformacoesRouteImport.update({
  id: '/informacoes',
  path: '/informacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacaoRoute = ConfirmacaoRouteImport.update({
  id: '/confirmacao',
  path: '/confirmacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoSucessoRoute = PagamentoSucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => PagamentoRoute,
} as any)
const PagamentoPendenteRoute = PagamentoPendenteRouteImport.update({
  id: '/pendente',
  path: '/pendente',
  getParentRoute: () => PagamentoRoute,
} as any)
const PagamentoFalhaRoute = PagamentoFalhaRouteImport.update({
  id: '/falha',
  path: '/falha',
  getParentRoute: () => PagamentoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/informacoes': typeof InformacoesRoute
  '/pagamento': typeof PagamentoRouteWithChildren
  '/presentes': typeof PresentesRoute
  '/pagamento/falha': typeof PagamentoFalhaRoute
  '/pagamento/pendente': typeof PagamentoPendenteRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/informacoes': typeof InformacoesRoute
  '/pagamento': typeof PagamentoRouteWithChildren
  '/presentes': typeof PresentesRoute
  '/pagamento/falha': typeof PagamentoFalhaRoute
  '/pagamento/pendente': typeof PagamentoPendenteRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/informacoes': typeof InformacoesRoute
  '/pagamento': typeof PagamentoRouteWithChildren
  '/presentes': typeof PresentesRoute
  '/pagamento/falha': typeof PagamentoFalhaRoute
  '/pagamento/pendente': typeof PagamentoPendenteRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/confirmacao'
    | '/informacoes'
    | '/pagamento'
    | '/presentes'
    | '/pagamento/falha'
    | '/pagamento/pendente'
    | '/pagamento/sucesso'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/confirmacao'
    | '/informacoes'
    | '/pagamento'
    | '/presentes'
    | '/pagamento/falha'
    | '/pagamento/pendente'
    | '/pagamento/sucesso'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/confirmacao'
    | '/informacoes'
    | '/pagamento'
    | '/presentes'
    | '/pagamento/falha'
    | '/pagamento/pendente'
    | '/pagamento/sucesso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ConfirmacaoRoute: typeof ConfirmacaoRoute
  InformacoesRoute: typeof InformacoesRoute
  PagamentoRoute: typeof PagamentoRouteWithChildren
  PresentesRoute: typeof PresentesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/presentes': {
      id: '/presentes'
      path: '/presentes'
      fullPath: '/presentes'
      preLoaderRoute: typeof PresentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informacoes': {
      id: '/informacoes'
      path: '/informacoes'
      fullPath: '/informacoes'
      preLoaderRoute: typeof InformacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacao': {
      id: '/confirmacao'
      path: '/confirmacao'
      fullPath: '/confirmacao'
      preLoaderRoute: typeof ConfirmacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/sucesso': {
      id: '/pagamento/sucesso'
      path: '/sucesso'
      fullPath: '/pagamento/sucesso'
      preLoaderRoute: typeof PagamentoSucessoRouteImport
      parentRoute: typeof PagamentoRoute
    }
    '/pagamento/pendente': {
      id: '/pagamento/pendente'
      path: '/pendente'
      fullPath: '/pagamento/pendente'
      preLoaderRoute: typeof PagamentoPendenteRouteImport
      parentRoute: typeof PagamentoRoute
    }
    '/pagamento/falha': {
      id: '/pagamento/falha'
      path: '/falha'
      fullPath: '/pagamento/falha'
      preLoaderRoute: typeof PagamentoFalhaRouteImport
      parentRoute: typeof PagamentoRoute
    }
  }
}

interface PagamentoRouteChildren {
  PagamentoFalhaRoute: typeof PagamentoFalhaRoute
  PagamentoPendenteRoute: typeof PagamentoPendenteRoute
  PagamentoSucessoRoute: typeof PagamentoSucessoRoute
}

const PagamentoRouteChildren: PagamentoRouteChildren = {
  PagamentoFalhaRoute: PagamentoFalhaRoute,
  PagamentoPendenteRoute: PagamentoPendenteRoute,
  PagamentoSucessoRoute: PagamentoSucessoRoute,
}

const PagamentoRouteWithChildren = PagamentoRoute._addFileChildren(
  PagamentoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  ConfirmacaoRoute: ConfirmacaoRoute,
  InformacoesRoute: InformacoesRoute,
  PagamentoRoute: PagamentoRouteWithChildren,
  PresentesRoute: PresentesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
